### ISSUE TITLE
Implement custom YAML (or other format) schema for mcmicro args to replace nextflow -params-file

### ISSUE THREAD

**Issue by jmuhlich** [labsyspharm/mcmicro#382]

**Comment by ArtemSokolov** [comment]
E.g., implement support for
```
in: /n/scratch3/users/m/maa6043/OVCA2med
unmict-opts:
  tool: unmicst-solo
  classorder: 1 0 2
  channel: 1
```
in place of the single-level
```
in: /n/scratch3/users/m/maa6043/OVCA2med
unmicst-opts: --tool unmicst-solo --classOrder 1 0 2 --channel 1
```
