### ISSUE TITLE
Introduce a models: parameter namespace

### ISSUE THREAD

**Issue by ArtemSokolov** [labsyspharm/mcmicro#417]
The `models:` namespace would allow users to do things like:

``` yaml
workflow:
  segmentation: [ilastik, mesmer]
models:
  ilastik: mymodel.ilp
  mesmer: membrane.tif
modules:
  segmentation:
    -
      name: ilastik
      model: --model
    -
      name: mesmer
      model: --membrane-image
```

To maintain backwards compatibility with `--ilastik-model`, the matching of double-dashed parameters against named modules in `modules:` can be done the same way as what is currently implemented for `options:` in https://github.com/labsyspharm/mcmicro/blob/b514a4c9b25d9ccae9f1ef0c6916edb3971fff58/lib/mcmicro/Opts.groovy#L95-L99
