### ISSUE TITLE
Expand the channel specification

### ISSUE THREAD

**Issue by ArtemSokolov** [labsyspharm/mcmicro#427]
Expand the current simple:

```
workflow:
  segmentation-channel: 1 5
```

to a more structured:

```
workflow:
  segmentation-channel:
    nucleus: 1 5
    cytoplasm: 2
    membrane: 3
    tissue: 4
```

Introduce the matching fields in `modules:` specification. For example:

```
modules:
  segmentation:
    -
      name: mesmer
      channel:
        nucleus: --nuclear-channel
        membrane: --membrane-channel
    -
      name: cypository
      channel:
        cytoplasm: --channel
  watershed:
    channel:
      nucleus: --probMapChan
      cytoplasm: --CytoMaskChan
      tissue: --TissueMaskChan
```
