### ISSUE TITLE
Introduce a `supplement` subdirectory

### ISSUE THREAD

**Issue by ArtemSokolov** [labsyspharm/mcmicro#435]
Allow users to add a `supplement/` subdirectory to their projects. All files in `supplement` will always be staged for each process, which will allow users to place things like custom models and metadata files there and have access to them when needed.

This is an alternative to #417 and allows users to simply do:

```
workflow:
  segmentation: [ilastik, mesmer]
options:
  ilastik: --model mymodel.ilp
  mesmer: --membrane-image membrane.tif
```

where `mymodel.ilp` and `membrane.tif` have been placed inside `supplement/`, making them available during ilastik and mesmer execution.
