### ISSUE TITLE
Allow for specifying a parameter grid

### ISSUE THREAD

**Issue by ArtemSokolov** [labsyspharm/mcmicro#441]
Allow users to specify a set of parameter values for parallel processing. An example interface:

``` yaml
options:
  ashlar:
    maximum-shift: [15, 30]
  s3seg:
    logSigma:
      - 25 200
      - 30 200
      - 40 220
```

which would run all pairings of ASHLAR with `-m 15` / `-m 30` against S3segmenter with `--logSigma 25 200` / `--logSigma 30 200` / `--log 40 220` for a total of 6 combinations.
