### ISSUE TITLE
segementation using cell pose

### ISSUE THREAD

**Issue by yas92** [labsyspharm/mcmicro#547]
I used cell pose for segmentation using MCMICRO and found that some cells are undersegmented while viewing in segmentation mask. 
Is there any threshold to adjust in param.yml file.

Your response will be very appreciated.
[param.yml.txt](https://github.com/labsyspharm/mcmicro/files/15033773/param.yml.txt)

**Comment by kbestak** [comment]
Hi, I would suggest adjusting the `diameter`, `flow_threshold` and `cellprob_threshold` parameters for Cellpose. [Here](https://cellpose.readthedocs.io/en/latest/cli.html#algorithm-arguments), you can find the explanations of those three parameters. 
You can provide the parameters to the pipeline with the `options` block in the params file, like this: 
```
workflow:
  start-at: segmentation
  stop-at: downstream
  viz: true
  segmentation-recyze: false
  segmentation: cellpose
  downstream: scimap
options:
  cellpose: --pretrained_model cyto --no_npy --diameter 20 --flow_threshold 0.6
```
