### ISSUE TITLE
Best practices for fibroblast detection

### ISSUE THREAD

**Issue by emir-radkevich** [labsyspharm/mcmicro#573]
Hi.

I have FAP (=fibroblasts channel) and Hoechst (=nuclei channel) in a panel. I was trying to use cytoplasm marker information:

```
options:
  s3seg: --CytoMaskChan 9 --segmentCytoplasm segmentCytoplasm
```

I also tried to use `--expand-size 5` argument:

```
options:
  s3seg: --expand-size 5

modules:
  watershed:
    name: s3seg
    container: labsyspharm/s3segmenter
    version: 1.5.4-large
```

I wouldn't say it went well. At least I do not see much of improvement comparing to using just nuclei channel information.

Could you please advice on how to detect fibroblasts in cancerous tissue? I do see [troubleshooting](https://mcmicro.org/troubleshooting/tuning/s3seg.html#4-a-how-do-i-segment-the-cytoplasm-as-well), but are there are other tips you could share?

Thank you,
Emir.
