### ISSUE TITLE
Autominerva do not show my image

### ISSUE THREAD

**Issue by tkcaccia** [labsyspharm/mcmicro#578]
I have a multi-immunofluorescent image with 7 channels: DAPI, PDL1, FOXP3, Ki67, CD4, HMW cytokeratin, autofluorescence.

The folder vis is create and populated by all files and folder. When I open the file index.html, the MINERVA is open but there is not the image of the tissue

**Comment by ArtemSokolov** [comment]
Hi @tkcaccia,

If you check the `.jpg` images in the `viz` directory, do they look correct or are they empty?

**Comment by tkcaccia** [comment]
There are not empty but their quality is not good.
I am able to open the image correctly with QuPath. Maybe this problem is related as well as why the segmentation fails

![Image](https://github.com/user-attachments/assets/257e0da6-bf7e-49d7-b321-c1b1a9ba40af)

**Comment by ArtemSokolov** [comment]
Yea, that just looks like white noise to me. Does this match what you see in `raw/` and `registration/`? At what step in the pipeline does your signal disappear?

**Comment by tkcaccia** [comment]
My image is an ome.tiff in 16 bit with 7 channels. 

My params.yml

```
workflow:
  start-at: registration        
  stop-at: quantification         
  segmentation: unmicst  
  segmentation-channel: 1
  viz: true                    

options:
  s3seg: --nucleiRegion localMax
```
My original image:
![Image](https://github.com/user-attachments/assets/32eddb19-4d33-4809-affe-17dce085337d)

In the folder raw the image is changed and looks empty. The scale of each channel is changed.

Registration image:
![Image](https://github.com/user-attachments/assets/bca6276e-5263-4dfe-95cc-c713c4a4010a)

The registration image showed some problems
